package sys.model.pacientes;
// Generated 17-jul-2018 21:17:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ControlPlaca generated by hbm2java
 */
public class ControlPlaca  implements java.io.Serializable {


     private Integer id;
     private Paciente paciente;
     private String estado;
     private String numDientes;
     private String numSuperficies;
     private String superficiesPlaca;
     private String extensionPlaca;
     private String dientes;
     private Set<Consultas> consultases = new HashSet<Consultas>(0);

    public ControlPlaca() {
    }

    public ControlPlaca(Paciente paciente, String estado, String numDientes, String numSuperficies, String superficiesPlaca, String extensionPlaca, String dientes, Set<Consultas> consultases) {
       this.paciente = paciente;
       this.estado = estado;
       this.numDientes = numDientes;
       this.numSuperficies = numSuperficies;
       this.superficiesPlaca = superficiesPlaca;
       this.extensionPlaca = extensionPlaca;
       this.dientes = dientes;
       this.consultases = consultases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getNumDientes() {
        return this.numDientes;
    }
    
    public void setNumDientes(String numDientes) {
        this.numDientes = numDientes;
    }
    public String getNumSuperficies() {
        return this.numSuperficies;
    }
    
    public void setNumSuperficies(String numSuperficies) {
        this.numSuperficies = numSuperficies;
    }
    public String getSuperficiesPlaca() {
        return this.superficiesPlaca;
    }
    
    public void setSuperficiesPlaca(String superficiesPlaca) {
        this.superficiesPlaca = superficiesPlaca;
    }
    public String getExtensionPlaca() {
        return this.extensionPlaca;
    }
    
    public void setExtensionPlaca(String extensionPlaca) {
        this.extensionPlaca = extensionPlaca;
    }
    public String getDientes() {
        return this.dientes;
    }
    
    public void setDientes(String dientes) {
        this.dientes = dientes;
    }
    public Set<Consultas> getConsultases() {
        return this.consultases;
    }
    
    public void setConsultases(Set<Consultas> consultases) {
        this.consultases = consultases;
    }




}


