package sys.model.pacientes;
// Generated 17-jul-2018 21:17:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DireccionPaciente generated by hbm2java
 */
public class DireccionPaciente  implements java.io.Serializable {


     private Integer id;
     private String pais;
     private String estado;
     private String ciudad;
     private String calle;
     private String colonia;
     private Set<Paciente> pacientes = new HashSet<Paciente>(0);

    public DireccionPaciente() {
    }

	
    public DireccionPaciente(String pais, String estado, String ciudad, String calle, String colonia) {
        this.pais = pais;
        this.estado = estado;
        this.ciudad = ciudad;
        this.calle = calle;
        this.colonia = colonia;
    }
    public DireccionPaciente(String pais, String estado, String ciudad, String calle, String colonia, Set<Paciente> pacientes) {
       this.pais = pais;
       this.estado = estado;
       this.ciudad = ciudad;
       this.calle = calle;
       this.colonia = colonia;
       this.pacientes = pacientes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public Set<Paciente> getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set<Paciente> pacientes) {
        this.pacientes = pacientes;
    }




}


