package sys.model.pacientes;
// Generated 17-jul-2018 21:17:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ExamenOral generated by hbm2java
 */
public class ExamenOral  implements java.io.Serializable {


     private Integer id;
     private String dolor;
     private String dolorOrgano;
     private String dolorUbicacion;
     private Date dolorDuracion;
     private String dolorEstimulo;
     private String lesionPulpar;
     private String exposicionPulpar;
     private String inflamacion;
     private String percusionOrgano;
     private String percusionVertical;
     private String percusionHorizontal;
     private String percusionPalpacion;
     private String frioOrgano;
     private String frioEstado;
     private String calorOrgano;
     private String calorEstado;
     private Set<ExamenOrofacial> examenOrofacials = new HashSet<ExamenOrofacial>(0);

    public ExamenOral() {
    }

	
    public ExamenOral(String dolor, String lesionPulpar, String exposicionPulpar, String inflamacion) {
        this.dolor = dolor;
        this.lesionPulpar = lesionPulpar;
        this.exposicionPulpar = exposicionPulpar;
        this.inflamacion = inflamacion;
    }
    public ExamenOral(String dolor, String dolorOrgano, String dolorUbicacion, Date dolorDuracion, String dolorEstimulo, String lesionPulpar, String exposicionPulpar, String inflamacion, String percusionOrgano, String percusionVertical, String percusionHorizontal, String percusionPalpacion, String frioOrgano, String frioEstado, String calorOrgano, String calorEstado, Set<ExamenOrofacial> examenOrofacials) {
       this.dolor = dolor;
       this.dolorOrgano = dolorOrgano;
       this.dolorUbicacion = dolorUbicacion;
       this.dolorDuracion = dolorDuracion;
       this.dolorEstimulo = dolorEstimulo;
       this.lesionPulpar = lesionPulpar;
       this.exposicionPulpar = exposicionPulpar;
       this.inflamacion = inflamacion;
       this.percusionOrgano = percusionOrgano;
       this.percusionVertical = percusionVertical;
       this.percusionHorizontal = percusionHorizontal;
       this.percusionPalpacion = percusionPalpacion;
       this.frioOrgano = frioOrgano;
       this.frioEstado = frioEstado;
       this.calorOrgano = calorOrgano;
       this.calorEstado = calorEstado;
       this.examenOrofacials = examenOrofacials;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDolor() {
        return this.dolor;
    }
    
    public void setDolor(String dolor) {
        this.dolor = dolor;
    }
    public String getDolorOrgano() {
        return this.dolorOrgano;
    }
    
    public void setDolorOrgano(String dolorOrgano) {
        this.dolorOrgano = dolorOrgano;
    }
    public String getDolorUbicacion() {
        return this.dolorUbicacion;
    }
    
    public void setDolorUbicacion(String dolorUbicacion) {
        this.dolorUbicacion = dolorUbicacion;
    }
    public Date getDolorDuracion() {
        return this.dolorDuracion;
    }
    
    public void setDolorDuracion(Date dolorDuracion) {
        this.dolorDuracion = dolorDuracion;
    }
    public String getDolorEstimulo() {
        return this.dolorEstimulo;
    }
    
    public void setDolorEstimulo(String dolorEstimulo) {
        this.dolorEstimulo = dolorEstimulo;
    }
    public String getLesionPulpar() {
        return this.lesionPulpar;
    }
    
    public void setLesionPulpar(String lesionPulpar) {
        this.lesionPulpar = lesionPulpar;
    }
    public String getExposicionPulpar() {
        return this.exposicionPulpar;
    }
    
    public void setExposicionPulpar(String exposicionPulpar) {
        this.exposicionPulpar = exposicionPulpar;
    }
    public String getInflamacion() {
        return this.inflamacion;
    }
    
    public void setInflamacion(String inflamacion) {
        this.inflamacion = inflamacion;
    }
    public String getPercusionOrgano() {
        return this.percusionOrgano;
    }
    
    public void setPercusionOrgano(String percusionOrgano) {
        this.percusionOrgano = percusionOrgano;
    }
    public String getPercusionVertical() {
        return this.percusionVertical;
    }
    
    public void setPercusionVertical(String percusionVertical) {
        this.percusionVertical = percusionVertical;
    }
    public String getPercusionHorizontal() {
        return this.percusionHorizontal;
    }
    
    public void setPercusionHorizontal(String percusionHorizontal) {
        this.percusionHorizontal = percusionHorizontal;
    }
    public String getPercusionPalpacion() {
        return this.percusionPalpacion;
    }
    
    public void setPercusionPalpacion(String percusionPalpacion) {
        this.percusionPalpacion = percusionPalpacion;
    }
    public String getFrioOrgano() {
        return this.frioOrgano;
    }
    
    public void setFrioOrgano(String frioOrgano) {
        this.frioOrgano = frioOrgano;
    }
    public String getFrioEstado() {
        return this.frioEstado;
    }
    
    public void setFrioEstado(String frioEstado) {
        this.frioEstado = frioEstado;
    }
    public String getCalorOrgano() {
        return this.calorOrgano;
    }
    
    public void setCalorOrgano(String calorOrgano) {
        this.calorOrgano = calorOrgano;
    }
    public String getCalorEstado() {
        return this.calorEstado;
    }
    
    public void setCalorEstado(String calorEstado) {
        this.calorEstado = calorEstado;
    }
    public Set<ExamenOrofacial> getExamenOrofacials() {
        return this.examenOrofacials;
    }
    
    public void setExamenOrofacials(Set<ExamenOrofacial> examenOrofacials) {
        this.examenOrofacials = examenOrofacials;
    }




}


