package sys.model.pacientes;
// Generated 17-jul-2018 21:17:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * HallazgosRadiograficos generated by hbm2java
 */
public class HallazgosRadiograficos  implements java.io.Serializable {


     private Integer id;
     private String tipoRx;
     private String soporteOseo;
     private String relacionCoronaRaiz;
     private String alturaReborde;
     private String engrosamientoLigamentoPeriodontal;
     private String interpretacion;
     private Set<ExamenOrofacial> examenOrofacials = new HashSet<ExamenOrofacial>(0);

    public HallazgosRadiograficos() {
    }

	
    public HallazgosRadiograficos(String tipoRx, String soporteOseo, String relacionCoronaRaiz, String alturaReborde, String engrosamientoLigamentoPeriodontal, String interpretacion) {
        this.tipoRx = tipoRx;
        this.soporteOseo = soporteOseo;
        this.relacionCoronaRaiz = relacionCoronaRaiz;
        this.alturaReborde = alturaReborde;
        this.engrosamientoLigamentoPeriodontal = engrosamientoLigamentoPeriodontal;
        this.interpretacion = interpretacion;
    }
    public HallazgosRadiograficos(String tipoRx, String soporteOseo, String relacionCoronaRaiz, String alturaReborde, String engrosamientoLigamentoPeriodontal, String interpretacion, Set<ExamenOrofacial> examenOrofacials) {
       this.tipoRx = tipoRx;
       this.soporteOseo = soporteOseo;
       this.relacionCoronaRaiz = relacionCoronaRaiz;
       this.alturaReborde = alturaReborde;
       this.engrosamientoLigamentoPeriodontal = engrosamientoLigamentoPeriodontal;
       this.interpretacion = interpretacion;
       this.examenOrofacials = examenOrofacials;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipoRx() {
        return this.tipoRx;
    }
    
    public void setTipoRx(String tipoRx) {
        this.tipoRx = tipoRx;
    }
    public String getSoporteOseo() {
        return this.soporteOseo;
    }
    
    public void setSoporteOseo(String soporteOseo) {
        this.soporteOseo = soporteOseo;
    }
    public String getRelacionCoronaRaiz() {
        return this.relacionCoronaRaiz;
    }
    
    public void setRelacionCoronaRaiz(String relacionCoronaRaiz) {
        this.relacionCoronaRaiz = relacionCoronaRaiz;
    }
    public String getAlturaReborde() {
        return this.alturaReborde;
    }
    
    public void setAlturaReborde(String alturaReborde) {
        this.alturaReborde = alturaReborde;
    }
    public String getEngrosamientoLigamentoPeriodontal() {
        return this.engrosamientoLigamentoPeriodontal;
    }
    
    public void setEngrosamientoLigamentoPeriodontal(String engrosamientoLigamentoPeriodontal) {
        this.engrosamientoLigamentoPeriodontal = engrosamientoLigamentoPeriodontal;
    }
    public String getInterpretacion() {
        return this.interpretacion;
    }
    
    public void setInterpretacion(String interpretacion) {
        this.interpretacion = interpretacion;
    }
    public Set<ExamenOrofacial> getExamenOrofacials() {
        return this.examenOrofacials;
    }
    
    public void setExamenOrofacials(Set<ExamenOrofacial> examenOrofacials) {
        this.examenOrofacials = examenOrofacials;
    }




}


