package sys.model.pacientes;
// Generated 17-jul-2018 21:17:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer id;
     private DireccionPaciente direccionPaciente;
     private MedicoPaciente medicoPaciente;
     private TrabajoPaciente trabajoPaciente;
     private String folio;
     private String nombre;
     private int edad;
     private String sexo;
     private Date fechaNacim;
     private String telefono;
     private String estatura;
     private String peso;
     private String estadoCivil;
     private String nivelEstudios;
     private String estadoSalud;
     private String porqueSolicita;
     private String observaciones;
     private Date fechaRegistro;
     private Set<ControlPlaca> controlPlacas = new HashSet<ControlPlaca>(0);
     private Set<ExamenOrofacial> examenOrofacials = new HashSet<ExamenOrofacial>(0);
     private Set<PlanTratamiento> planTratamientos = new HashSet<PlanTratamiento>(0);
     private Set<PreguntasPaciente> preguntasPacientes = new HashSet<PreguntasPaciente>(0);
     private Set<Periodontograma> periodontogramas = new HashSet<Periodontograma>(0);
     private Set<Consultas> consultases = new HashSet<Consultas>(0);

    public Paciente() {
    }

	
    public Paciente(DireccionPaciente direccionPaciente, MedicoPaciente medicoPaciente, TrabajoPaciente trabajoPaciente, String folio, String nombre, int edad, String sexo, Date fechaNacim, String telefono, String estatura, String peso, String estadoCivil, String nivelEstudios, String estadoSalud, String porqueSolicita, String observaciones, Date fechaRegistro) {
        this.direccionPaciente = direccionPaciente;
        this.medicoPaciente = medicoPaciente;
        this.trabajoPaciente = trabajoPaciente;
        this.folio = folio;
        this.nombre = nombre;
        this.edad = edad;
        this.sexo = sexo;
        this.fechaNacim = fechaNacim;
        this.telefono = telefono;
        this.estatura = estatura;
        this.peso = peso;
        this.estadoCivil = estadoCivil;
        this.nivelEstudios = nivelEstudios;
        this.estadoSalud = estadoSalud;
        this.porqueSolicita = porqueSolicita;
        this.observaciones = observaciones;
        this.fechaRegistro = fechaRegistro;
    }
    public Paciente(DireccionPaciente direccionPaciente, MedicoPaciente medicoPaciente, TrabajoPaciente trabajoPaciente, String folio, String nombre, int edad, String sexo, Date fechaNacim, String telefono, String estatura, String peso, String estadoCivil, String nivelEstudios, String estadoSalud, String porqueSolicita, String observaciones, Date fechaRegistro, Set<ControlPlaca> controlPlacas, Set<ExamenOrofacial> examenOrofacials, Set<PlanTratamiento> planTratamientos, Set<PreguntasPaciente> preguntasPacientes, Set<Periodontograma> periodontogramas, Set<Consultas> consultases) {
       this.direccionPaciente = direccionPaciente;
       this.medicoPaciente = medicoPaciente;
       this.trabajoPaciente = trabajoPaciente;
       this.folio = folio;
       this.nombre = nombre;
       this.edad = edad;
       this.sexo = sexo;
       this.fechaNacim = fechaNacim;
       this.telefono = telefono;
       this.estatura = estatura;
       this.peso = peso;
       this.estadoCivil = estadoCivil;
       this.nivelEstudios = nivelEstudios;
       this.estadoSalud = estadoSalud;
       this.porqueSolicita = porqueSolicita;
       this.observaciones = observaciones;
       this.fechaRegistro = fechaRegistro;
       this.controlPlacas = controlPlacas;
       this.examenOrofacials = examenOrofacials;
       this.planTratamientos = planTratamientos;
       this.preguntasPacientes = preguntasPacientes;
       this.periodontogramas = periodontogramas;
       this.consultases = consultases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DireccionPaciente getDireccionPaciente() {
        return this.direccionPaciente;
    }
    
    public void setDireccionPaciente(DireccionPaciente direccionPaciente) {
        this.direccionPaciente = direccionPaciente;
    }
    public MedicoPaciente getMedicoPaciente() {
        return this.medicoPaciente;
    }
    
    public void setMedicoPaciente(MedicoPaciente medicoPaciente) {
        this.medicoPaciente = medicoPaciente;
    }
    public TrabajoPaciente getTrabajoPaciente() {
        return this.trabajoPaciente;
    }
    
    public void setTrabajoPaciente(TrabajoPaciente trabajoPaciente) {
        this.trabajoPaciente = trabajoPaciente;
    }
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNacim() {
        return this.fechaNacim;
    }
    
    public void setFechaNacim(Date fechaNacim) {
        this.fechaNacim = fechaNacim;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEstatura() {
        return this.estatura;
    }
    
    public void setEstatura(String estatura) {
        this.estatura = estatura;
    }
    public String getPeso() {
        return this.peso;
    }
    
    public void setPeso(String peso) {
        this.peso = peso;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getNivelEstudios() {
        return this.nivelEstudios;
    }
    
    public void setNivelEstudios(String nivelEstudios) {
        this.nivelEstudios = nivelEstudios;
    }
    public String getEstadoSalud() {
        return this.estadoSalud;
    }
    
    public void setEstadoSalud(String estadoSalud) {
        this.estadoSalud = estadoSalud;
    }
    public String getPorqueSolicita() {
        return this.porqueSolicita;
    }
    
    public void setPorqueSolicita(String porqueSolicita) {
        this.porqueSolicita = porqueSolicita;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<ControlPlaca> getControlPlacas() {
        return this.controlPlacas;
    }
    
    public void setControlPlacas(Set<ControlPlaca> controlPlacas) {
        this.controlPlacas = controlPlacas;
    }
    public Set<ExamenOrofacial> getExamenOrofacials() {
        return this.examenOrofacials;
    }
    
    public void setExamenOrofacials(Set<ExamenOrofacial> examenOrofacials) {
        this.examenOrofacials = examenOrofacials;
    }
    public Set<PlanTratamiento> getPlanTratamientos() {
        return this.planTratamientos;
    }
    
    public void setPlanTratamientos(Set<PlanTratamiento> planTratamientos) {
        this.planTratamientos = planTratamientos;
    }
    public Set<PreguntasPaciente> getPreguntasPacientes() {
        return this.preguntasPacientes;
    }
    
    public void setPreguntasPacientes(Set<PreguntasPaciente> preguntasPacientes) {
        this.preguntasPacientes = preguntasPacientes;
    }
    public Set<Periodontograma> getPeriodontogramas() {
        return this.periodontogramas;
    }
    
    public void setPeriodontogramas(Set<Periodontograma> periodontogramas) {
        this.periodontogramas = periodontogramas;
    }
    public Set<Consultas> getConsultases() {
        return this.consultases;
    }
    
    public void setConsultases(Set<Consultas> consultases) {
        this.consultases = consultases;
    }




}


