package sys.model.pacientes;
// Generated 17-jul-2018 21:17:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Periodontograma generated by hbm2java
 */
public class Periodontograma  implements java.io.Serializable {


     private Integer id;
     private Paciente paciente;
     private String estado;
     private String dientes;
     private Set<Consultas> consultases = new HashSet<Consultas>(0);

    public Periodontograma() {
    }

    public Periodontograma(Paciente paciente, String estado, String dientes, Set<Consultas> consultases) {
       this.paciente = paciente;
       this.estado = estado;
       this.dientes = dientes;
       this.consultases = consultases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getDientes() {
        return this.dientes;
    }
    
    public void setDientes(String dientes) {
        this.dientes = dientes;
    }
    public Set<Consultas> getConsultases() {
        return this.consultases;
    }
    
    public void setConsultases(Set<Consultas> consultases) {
        this.consultases = consultases;
    }




}


