package sys.model.pacientes;
// Generated 17-jul-2018 21:17:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TrabajoPaciente generated by hbm2java
 */
public class TrabajoPaciente  implements java.io.Serializable {


     private Integer id;
     private String ocupacion;
     private String lugarTrabajo;
     private String telefonoTrabajo;
     private Set<Paciente> pacientes = new HashSet<Paciente>(0);

    public TrabajoPaciente() {
    }

	
    public TrabajoPaciente(String ocupacion, String lugarTrabajo, String telefonoTrabajo) {
        this.ocupacion = ocupacion;
        this.lugarTrabajo = lugarTrabajo;
        this.telefonoTrabajo = telefonoTrabajo;
    }
    public TrabajoPaciente(String ocupacion, String lugarTrabajo, String telefonoTrabajo, Set<Paciente> pacientes) {
       this.ocupacion = ocupacion;
       this.lugarTrabajo = lugarTrabajo;
       this.telefonoTrabajo = telefonoTrabajo;
       this.pacientes = pacientes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getLugarTrabajo() {
        return this.lugarTrabajo;
    }
    
    public void setLugarTrabajo(String lugarTrabajo) {
        this.lugarTrabajo = lugarTrabajo;
    }
    public String getTelefonoTrabajo() {
        return this.telefonoTrabajo;
    }
    
    public void setTelefonoTrabajo(String telefonoTrabajo) {
        this.telefonoTrabajo = telefonoTrabajo;
    }
    public Set<Paciente> getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set<Paciente> pacientes) {
        this.pacientes = pacientes;
    }




}


